/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_12 (
    input z,
    input v,
    input n,
    input [5:0] alufn,
    output reg [15:0] out,
    output reg [2:0] error
  );
  
  
  
  always @* begin
    out = 16'h0000;
    error = 3'h0;
    
    case (alufn[1+1-:2])
      2'h1: begin
        out[0+0-:1] = z;
      end
      2'h2: begin
        out[0+0-:1] = n ^ v;
      end
      2'h3: begin
        out[0+0-:1] = z | (n ^ v);
      end
      default: begin
        error = 3'h2;
      end
    endcase
  end
endmodule
