/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module zvnvalues_15 (
    input [15:0] a,
    input [15:0] b,
    input [15:0] sout,
    input [5:0] alufn,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  always @* begin
    z = (~|(sout));
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn[0+0-:1]) & !sout[15+0-:1]) | (!a[15+0-:1] & !(b[15+0-:1] ^ alufn[0+0-:1]) & sout[15+0-:1]);
    n = sout[15+0-:1];
  end
endmodule
